name: Frontend App
on:
  push:
    branches: ["main"]

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}   
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_PRIVATE: ${{secrets.AWS_SSH_KEY_PRIVATE}}
  SERVER_PUBLIC_IP: ${{secrets.SERVER_PUBLIC_IP}}
  USERNAME: ${{secrets.SERVER_USERNAME}}
  AWS_REGION: us-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/Checkout@v2
      - name: SSH to server for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_PUBLIC_IP }}
          username: ${{ env.USERNAME}}
          key: ${{ env.AWS_PRIVATE }}
          script: |-
            sudo apt-get update
            sudo apt-get install git -y
            echo "--NODE & NPM--"
            sudo apt install nodejs -y
            sudo apt install npm -y
            echo "-----PM2------"
            sudo npm install -g pm2
            sudo pm2 startup systemd
            echo "-----NGINX------"
            sudo apt-get install -y nginx
            echo "---FIREWALL---"
            sudo ufw allow OpenSSH
            sudo ufw allow 'Nginx Full'
            sudo ufw --force enable 
            cd /home/ubuntu
            sudo rm -rf client || true
            git clone https://github.com/husseinalamutu/client.git
            cd memories-client
            npm install
            rm -rf build
            npm run build
            sudo pm2 kill
            sudo kill $(lsof -nt -i4TCP:3000)
            pm2 serve build/ 3000 -f --name "react-build" --spa
            sudo rm -rf /etc/nginx/sites-available/default
            sudo cp default /etc/nginx/sites-available/ -r
            sudo systemctl restart nginx

